POST http://localhost:3333/auth/register
Content-Type: application/json

{
    "email": "dalmi@gmail.com",
    "password": "123456"
}


###
POST http://localhost:3333/auth/login
Content-Type: application/json

{
    "email": "dalmi@gmail.com",
    "password": "123456"
}

###
GET http://localhost:3333/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZTE3ZGMyZS0yYTBhLTQwMGQtOTMyMi1mZGQwOWI2MWRiNmMiLCJlbWFpbCI6ImRhbG1pQGdtYWlsLmNvbSIsImlhdCI6MTcxMDEyNTEzMSwiZXhwIjoxNzEwMTI2MDMxfQ.Z2dqyoOwMOlji19kuJTvKBDrEbgYnh77kHuy1vfpm9g

