POST http://localhost:3333/auth/register
Content-Type: application/json

{
    "email": "oman@gmail.com",
    "password": "123456"
}


###
POST http://localhost:3333/auth/login
Content-Type: application/json

{
    "email": "oman@gmail.com",
    "password": "123456"
}

###
POST http://localhost:3333/auth/login-next
Content-Type: application/json

{
    "email": "oman@gmail.com",
    "password": "123456"
}

###
GET http://localhost:3333/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZTE3ZGMyZS0yYTBhLTQwMGQtOTMyMi1mZGQwOWI2MWRiNmMiLCJlbWFpbCI6ImRhbG1pQGdtYWlsLmNvbSIsImlhdCI6MTcxMDEyNTEzMSwiZXhwIjoxNzEwMTI2MDMxfQ.Z2dqyoOwMOlji19kuJTvKBDrEbgYnh77kHuy1vfpm9g

###
GET http://localhost:3333/bookmarks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5NDkyYzIwNy01NDhmLTQ5YzUtOWI2NC0xMmNiYmQ2OTllMTQiLCJlbWFpbCI6Im9tYW5AZ21haWwuY29tIiwiaWF0IjoxNzEwMTI5MjM3LCJleHAiOjE3MTAxMzAxMzd9.TZFfiNvK3P6UPtDVU59C9mnKw1Yx1ShVQ6rMBvew4pw

###
POST http://localhost:3333/bookmarks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5NDkyYzIwNy01NDhmLTQ5YzUtOWI2NC0xMmNiYmQ2OTllMTQiLCJlbWFpbCI6Im9tYW5AZ21haWwuY29tIiwiaWF0IjoxNzEwMTI5MjM3LCJleHAiOjE3MTAxMzAxMzd9.TZFfiNvK3P6UPtDVU59C9mnKw1Yx1ShVQ6rMBvew4pw

{
    "title": "Oman Second Bookmark",
    "description": "This is Oman Second bookmark",
    "link": "https://www.youtube.com/watch?v=PqGnP9pfZZU"
}

###
POST http://localhost:3333/users/search-by-email
Content-Type: application/json

{
    "email": "dalmi@gmail.com"
}